// <auto-generated />
using System;
using IvanWeb.Infrastructure.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace IvanWeb.Infrastructure.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20260720170243_store")]
    partial class store
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("IvanWeb.Domain.Entities.PlayerProfile", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("Daily8BitRuns")
                        .HasColumnType("integer");

                    b.Property<int>("DailyClockRuns")
                        .HasColumnType("integer");

                    b.Property<int>("DailyHardRuns")
                        .HasColumnType("integer");

                    b.Property<DateTime>("FirstRunDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("LastLoginAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("LastPlayedDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("LastQuizPlayedDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<int>("QuizCorrectAnswers")
                        .HasColumnType("integer");

                    b.Property<int>("QuizIncorrectAnswers")
                        .HasColumnType("integer");

                    b.Property<int>("QuizRuns")
                        .HasColumnType("integer");

                    b.Property<int>("QuizSongsCorrectAnswers")
                        .HasColumnType("integer");

                    b.Property<int>("QuizSongsIncorrectAnswers")
                        .HasColumnType("integer");

                    b.Property<int>("QuizSongsRuns")
                        .HasColumnType("integer");

                    b.Property<int>("RunCount")
                        .HasColumnType("integer");

                    b.Property<int>("TotalScore")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(0);

                    b.HasKey("Id");

                    b.ToTable("PlayerProfiles", (string)null);
                });

            modelBuilder.Entity("IvanWeb.Domain.Entities.PurchaseHistory", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("PlayerProfileId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("StoreItemId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("PlayerProfileId");

                    b.HasIndex("StoreItemId");

                    b.ToTable("PurchaseHistories", (string)null);
                });

            modelBuilder.Entity("IvanWeb.Domain.Entities.QuizQuestion", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Answer")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("IsAnswered")
                        .HasColumnType("boolean");

                    b.Property<int>("Points")
                        .HasColumnType("integer");

                    b.Property<string>("Question")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("QuizQuestions");
                });

            modelBuilder.Entity("IvanWeb.Domain.Entities.Song", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Artist")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("FileId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("Genre")
                        .HasColumnType("integer");

                    b.Property<bool>("Is8Bit")
                        .HasColumnType("boolean");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid?>("PlayerProfileId")
                        .HasColumnType("uuid");

                    b.Property<int>("Points")
                        .HasColumnType("integer");

                    b.Property<int>("Year")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("PlayerProfileId");

                    b.ToTable("Songs");
                });

            modelBuilder.Entity("IvanWeb.Domain.Entities.StoreItem", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Icon")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsSinglePurchase")
                        .HasColumnType("boolean");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<int>("Price")
                        .HasColumnType("integer");

                    b.Property<bool>("SendWhatsApp")
                        .HasColumnType("boolean");

                    b.HasKey("Id");

                    b.ToTable("StoreItems", (string)null);
                });

            modelBuilder.Entity("IvanWeb.Domain.Entities.Trophy", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<string>("Icon")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("IsSecret")
                        .HasColumnType("boolean");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)");

                    b.Property<int>("Points")
                        .HasColumnType("integer");

                    b.Property<string>("Rarity")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("Requirements")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("SecretHint")
                        .HasColumnType("text");

                    b.Property<string>("Slug")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.HasKey("Id");

                    b.HasIndex("Slug")
                        .IsUnique();

                    b.ToTable("Trophies", (string)null);
                });

            modelBuilder.Entity("IvanWeb.Domain.Entities.UnlockedTrophy", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("PlayerProfileId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("TrophyId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("UnlockedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("TrophyId");

                    b.HasIndex("PlayerProfileId", "TrophyId")
                        .IsUnique();

                    b.ToTable("UnlockedTrophies", (string)null);
                });

            modelBuilder.Entity("IvanWeb.Domain.Entities.PurchaseHistory", b =>
                {
                    b.HasOne("IvanWeb.Domain.Entities.PlayerProfile", "PlayerProfile")
                        .WithMany("Purchases")
                        .HasForeignKey("PlayerProfileId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("IvanWeb.Domain.Entities.StoreItem", "StoreItem")
                        .WithMany()
                        .HasForeignKey("StoreItemId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("PlayerProfile");

                    b.Navigation("StoreItem");
                });

            modelBuilder.Entity("IvanWeb.Domain.Entities.Song", b =>
                {
                    b.HasOne("IvanWeb.Domain.Entities.PlayerProfile", null)
                        .WithMany("GuessedSongs")
                        .HasForeignKey("PlayerProfileId");
                });

            modelBuilder.Entity("IvanWeb.Domain.Entities.UnlockedTrophy", b =>
                {
                    b.HasOne("IvanWeb.Domain.Entities.PlayerProfile", "PlayerProfile")
                        .WithMany("UnlockedTrophies")
                        .HasForeignKey("PlayerProfileId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("IvanWeb.Domain.Entities.Trophy", "Trophy")
                        .WithMany()
                        .HasForeignKey("TrophyId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("PlayerProfile");

                    b.Navigation("Trophy");
                });

            modelBuilder.Entity("IvanWeb.Domain.Entities.PlayerProfile", b =>
                {
                    b.Navigation("GuessedSongs");

                    b.Navigation("Purchases");

                    b.Navigation("UnlockedTrophies");
                });
#pragma warning restore 612, 618
        }
    }
}
